#:kivy 1.11.1

#:import Scene layout.scene.Scene
#:import Tools layout.tools.Tools
#:import LeftButtonWidget button.left_button
#:import RightButtonWidget button.right_button


<RideMeGame>:
    orientation: 'vertical'
    Scene:
    Tools:
        AnchorLayout:
            anchor_x: 'left'
            anchor_y: 'bottom'
            LeftButtonWidget:
        AnchorLayout:
            anchor_x: 'right'
            anchor_y: 'bottom'
            RightButtonWidget:
