#:import VisibleZone road.visible_zone.VisibleZone

<Road>:
    # -- repeat-wrap
    canvas.before:
        #Clear
        Rectangle:
            size: self.size
            pos: self.pos
            texture: self.texture


    # VisibleZone:
        #id: "VisibleZone"
        #canvas:
            #Color:
                #rgb: (.2, 0, 1)
            #Line:
                #width: 2
                #rectangle: self.rectangle()
