name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    

    steps:
      - uses: actions/checkout@v2
      
      - name: Install and activate venv
        run: |
          # cd ride_me,
          python3 -m virtualenv venv,
          . venv/bin/activate

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      
      - name: Tests
        run: |
          cd tests,
          pytest
      
