name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7.4, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9.0-beta.4'
    
      - name: Install and activate venv
        run: |
          # cd ride_me,
          python3 -m virtualenv venv,
          . venv/bin/activate

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
      
      - name: Tests
        run: |
          cd tests,
          pytest
      
